name: Build Docker image
on:
  push:
    branches:
      - main

env:
  build_id: ${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Harbor
        run: |
              echo ${{ secrets.DOCKERHUB_USERNAME }}
              echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login  ${{ secrets.HARBOR_REGISTRY_URL }} -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
